# Generated by Django 5.2 on 2025-04-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
    ]
