# Generated by Django 5.2 on 2025-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_useractivity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('create_note', 'Create_Note'), ('update_note', 'Update_Note'), ('delete_note', 'Delete_Note')], max_length=50),
        ),
    ]
