name: Django Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Install Dependencies
        run: |
          cd Backend_System
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          cd backend
          python manage.py migrate

      - name: Run Tests
        run: |
          cd Backend_System
          python manage.py test
